[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "plotly>=6.1.2",
    "scikit-learn>=1.7.0",
    "streamlit>=1.45.1",
    "tensorflow>=2.19.0",
    "yfinance>=0.2.61",
]
